# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://hcs87.github.io/pincapuca/"

git_url = "https://github.com/hcs87/pincapuca/tree/master/"

def custom_doc_links(name): return None
